version: '3.9'

services:
  nestjs-app:
    build: .
    container_name: nestjs-app
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
