version: '3.9'

services:
  nestjs-app:
    build: .
    container_name: nestjs-app
    restart: always
    ports:
      - '3000:3000'
    command: node dist/main
    env_file:
      - .env
    environment:
      - NODE_ENV=production
